### ISSUE TITLE
Bootloader Unlocking

### ISSUE THREAD

**Issue by ihtarlik** [falk0069/twrp_score7_mt8167#2]
I understand how TWRP images work (have done a lot with Android), but the versions of this device have the bootloader locked. How do you unlock the bootloader to allow for booting the TWRP image?

**Comment by falk0069** [comment]
Since it uses an MTK chip, you can use mtkclient.  Here is a link to a post I wrote with some of my experiences and steps:

Post in thread 'Custom ROM for Score 7 Keefe Group MT8167 Tablet' https://xdaforums.com/t/custom-rom-for-score-7-keefe-group-mt8167-tablet.4662278/post-89481201

**Comment by ihtarlik** [comment]
Aha. My mistake. This method only works for the Score 7, but not the 7C or 7T. BROM mode has been disabled by software in newer models.

For reference, @falk0069 suggests using mtkclient (Windows, Mac, or Linux) to unlock the bootloader and accomplish partition reading/writing. mtkclient has not been a viable option for later models due to secure boot being enabled and BROM being disabled.
